title: "<span style='white-space: nowrap;'>Yuhan Ye <span style='font-size:90%;'>(叶禹含)</span></span>"
description: "<p style='text-align:center; font-size:90%; color:gray; margin-top:-10px;'>
<a href='https://www.linkedin.com/in/yuhan-ye77/' style='color:gray; text-decoration:none;'>LinkedIn</a> │ 
<a href='https://www.sfi.ch/en/people/yuhan-ye' style='color:gray; text-decoration:none;'>SFI Profile</a> │ 
<a href='https://search.usi.ch/en/people/12fe19968bc63b6bdbe84d3eea7a5a4c/ye-yuhan' style='color:gray; text-decoration:none;'>USI Profile</a>
</p>"
theme: jekyll-theme-minimal
logo: /assets/profile.JPG
show_downloads: false
github:
  is_project_page: false
